# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b962aa799d0f7ef26cad6df0a25a988234bcd766e46ac5209d86797074c9a691ad1eebf3f44d8f74ade4482368746a1fa77dd2ef9378583108bea5578e62dc7c

test:
  secret_key_base: beaa092aa14831fccc6dc450bcea940c0bcabfa4e01fe06472387ba304b829461f514d6e2bcafd80a79934821e57417bed3de6d26a6510b33f92568f7789c76e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
